// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqRzyDDvtILj8BvRbSbyMs00WGpfFNaU',
    appId: '1:973356181852:web:3721de98fb48271b843999',
    messagingSenderId: '973356181852',
    projectId: 'social-media-app-e390c',
    authDomain: 'social-media-app-e390c.firebaseapp.com',
    storageBucket: 'social-media-app-e390c.firebasestorage.app',
    measurementId: 'G-JF403VELX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDI95jPNPeEWgXp1sod_BWA1bLkaBciaA',
    appId: '1:973356181852:android:281cd0f72d6c2b78843999',
    messagingSenderId: '973356181852',
    projectId: 'social-media-app-e390c',
    storageBucket: 'social-media-app-e390c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB206vWJF8bJ2Sy4ERQmCynZzFP4NdZqQ',
    appId: '1:973356181852:ios:225ee9eb346374ae843999',
    messagingSenderId: '973356181852',
    projectId: 'social-media-app-e390c',
    storageBucket: 'social-media-app-e390c.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
